// <auto-generated />
namespace SiteECommerce.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recup_valentin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recup_valentin));
        
        string IMigrationMetadata.Id
        {
            get { return "201607181503461_recup_valentin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
